### ISSUE TITLE
Using WindowsServer2022\HCL_build\setup\win22\efi\statisIP\autounattend.xml results in install unable to process answer file.

### ISSUE THREAD

**Issue by dmilhuisen** [brandonleegit/PackerBuilds#10]
Ussing the WindowsServer2022\HCL_build\setup\win22\efi\staticIP\autounattend.xml

Results in the following:

<img width="792" height="328" alt="Image" src="https://github.com/user-attachments/assets/53a9a053-6e09-4687-8e80-abd74a54df65" />

Only filled in details:
```xml


<Networking>
    <Interfaces>
        <Interface wcm:action="add" wcm:keyValue="1">
            <Ipv4Settings>
                <IpAddress>172.21.253.20</IpAddress>
                <SubnetMask>255.255.255.0</SubnetMask>
                <Gateway>172.21.253.254</Gateway>
                <DnsServers>
                    <DnsServer>172.21.253.1</DnsServer>
                    <DnsServer>172.21.253.2</DnsServer>
                </DnsServers>
            </Ipv4Settings>
        </Interface>
    </Interfaces>
</Networking>
```

**Comment by brandonleegit** [comment]
@dmilhuisen I just committed and pushed a fix to the autounattend.xml. Can you git fetch && git pull down the latest and try it again?

**Comment by dmilhuisen** [comment]
@brandonleegit thank you for the quick response, but it did not fix the static IP assignment, getting the auto assign IP address.
It did fix the setting missing the answer file.

```shell
==> vsphere-iso.autogenerated_1: Waiting for IP...
==> vsphere-iso.autogenerated_1: IP address: 169.254.103.229
==> vsphere-iso.autogenerated_1: Using WinRM communicator to connect: 169.254.103.229
==> vsphere-iso.autogenerated_1: Waiting for WinRM to become available...
```

**Comment by brandonleegit** [comment]
> [@brandonleegit](https://github.com/brandonleegit) thank you for the quick response, but it did not fix the static IP assignment, getting the auto assign IP address. It did fix the setting missing the answer file.
> 
> ==> vsphere-iso.autogenerated_1: Waiting for IP...
> ==> vsphere-iso.autogenerated_1: IP address: 169.254.103.229
> ==> vsphere-iso.autogenerated_1: Using WinRM communicator to connect: 169.254.103.229
> ==> vsphere-iso.autogenerated_1: Waiting for WinRM to become available...

I have committed a new .xml file. I think the previous one was setting the IP in the wrong pass, winPE. Can you try the new autounattend.xml?
